### ISSUE TITLE
[size limit]: compress history events payloads

### ISSUE THREAD

**Issue by yiminc-zz** [uber/cadence#1084]
There are different size limit in the system including Cassandra batch transaction size limit and Kafka message size limit for replication task.

We could compress payloads of history events to reduce the size.

**Comment by ibarrajo** [comment]
The Cadence team has dedicated time this year to address history compression, both at rest and in-flight.

If this is an urgent issue concerning the size of the history, you could use continue as new in order to truncate workflow history or store large data blobs on an object storage database instead of depending on Cadence to persist the arguments and results from workflows and activities.
