### ISSUE TITLE
System protection on size limit and number of events (activities)

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#1262]
activities are kept in a map within mutable state.  100K activities cause problems with cassandra tombstone issue.

**Comment by vancexu** [comment]
We already had a size and count limit for history, which is 200MB and 200K. Is this 100K activities not caught by history limit? do we want similar thing for activities?

**Comment by vancexu** [comment]
Tests on both local and prod showed that 100k activities will not cause Cassandra tombstone issue because workflow will be terminated because HISTORY_SIZE_EXCEEDS_LIMIT before causing any db problem. 
To not enforce more limits to cadence user, I think it would be better to not add limits on activity or childworkflow. 
In future if there are other requirements/reasons coming, we can evaluate then.
