### ISSUE TITLE
Business Process Engine

### ISSUE THREAD

**Issue by thesupercomb** [uber/cadence#1546]
We are creating a business process engine and looking at Cadence to be the execution engine.  The requirements may be slightly different than what Cadence was originally intended for and so I could use some help in comparing the requirements with what is reasonably to expect from the engine.

1 - We need sub 50ms response times in some instances.  Is it reasonable to expect that a worker could pull an activity that quickly?  What about for starting a workflow?

2- Almost all workflows will have open executions forever (or at least a few years.)  Could this be problematic down the line?  Our history list wouldn't be too long though.

Thanks for any help you can throw my way!

**Comment by samarabbas** [comment]
Hi @thesupercomb, Thanks for your interest in evaluating Cadence for your use case.  Here is my response to your questions:

1. Most of the Cadence service API provides under 50ms p99 latencies.  As for the worker pulling an activity in response to an external event for workflow execution, there are more roundtrips involved between Cadence worker and Cadence Server which makes it hard to meet your 50ms latency requirement.  We do provide primitives like "Local Activity" which might fit better for low latency use cases if your activities are not long running.  Another primitive to look into is "Query", which allows you to query any workflow execution without incurring any write and used to query state of a single workflow execution.  We are also working on a new [feature](https://github.com/uber/cadence/issues/538) which allows to send signal and synchronously respond back to caller.  This feature is very useful for scenario which require synchronous response from workflows to unblock callers.  Can you provide more details about your use case which requires such low latency?  It will help us provide better recommendation.
2. This is not a problem for Cadence at all.  It actually fits perfectly with Cadence model as lots of applications use Cadence workflows as fault tolerant/long live actors.  I highly recommend to watch @mfateev [presentation](https://www.youtube.com/watch?v=llmsBGKOuWI) which also talks about treating workflows as fault tolerant actors.

Also free to join our [slack channel](https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTI5Yzc5ODYwMjg1ZmI3NmRmMTU1MjQ0YzQyZDc5NzMwMmM0NjkzNDE5MmM0NzU5YTlhMmI4NzIzMDhiNzFjMDM) and ask questions there.

**Comment by thesupercomb** [comment]
A user will be on the website launches a workflow directly with a click of a button.  The job of the first activity is to figure out which page to redirect the user to depending on the country the user is from (the example is a bit contrived but I'm hoping that it accurately relays the requirement.)

This means that the User will be blocked until the Activity can get a response back.  We obviously want that window of time to be as small as possible.

The new feature you pointed me to looks promising, I can't tell though if I can pass information back through the activity as the reply.  But we could work that out later on.

Hope that answered your question.

**Comment by mfateev** [comment]
Yes, the update feature will support returning any information from the workflow. It would be similar to the query, but would be allowed to mutate the state of a workflow and execute local activities.

Until the update is available here is the workaround to implement blocking request/reply into the workflow:

- A process that initiates the request needs to host an activity that listens to a process specific task list. This is achieved by generating a unique processId on process startup and starting a Cadence worker that hosts the activity that listens on a task list with this process id. This activity is used to deliver the request result.
- The synchronous request first sends a signal to the workflow. The signal arguments include a unique requestId as well as processId. Then it creates a Channel and inserts it into a map using requestId as a key. Then the requesting thread blocks on this Channel receive.
- Upon receiving the signal the workflow performs all the necessary activities and state transitions. Then to reply the workflow invokes the deliver result activity using the processId as the task list name and passing requestId as one of the activity arguments.
- As the process specific task list is used the activity is executed in the same process that sent the original signal. Then it gets from the map the Channel that the original requested thread is blocked on and pushes to it the result of the request received as another activity argument.
- The original thread is unblocked by receiving the request result and can continue its execution.

For Java service use a CompletableFuture instead of a Channel.

**Comment by mfateev** [comment]
In you case you don't need to send the signal to initiate the request as you are starting a workflow and waiting for it reaching a certain state.
