### ISSUE TITLE
[Question] about use case

### ISSUE THREAD

**Issue by joecabezas** [uber/cadence#1889]
I am working in a project in which I am convinced it can be modeled as a workflow but I still not understand how Cadence can be helpful in out use case.

My idea was to use something like Step Functions, which will allow us to model our business logic in a workflow described in a DSL (like `Amazon States Language`), each node making calls to microservices deployed internally and depending on the return value, the orchrestrator advances to a next node, this process is then repeated across all nodes until it lands on a terminal node.

As requirements I would like to have an orchestrator that
* can handle retryability for us
* branching depending on each activity return value
* workflow defined as a DSL, allowing versioning and fast editing, language agnostic, like YAML or JSON
* be able to call microservices without the need to write an activity, just define in the same workflow DSL the endpoint to call and call it and move to the next node in the workflow depending on the return value, like `Amazon States Language` allow you to define a resource to use for that node:
https://states-language.net/spec.html#task-state

I tried Cadence and I am trying to understand if Cadence is what we want, is there something listed in the requirements that Cadence definitively can not do? What I am missing?

In Cadence, both the workflow and the activities need to be written in Go or Java, an activity can be coded to make an API call to our microservices, and the workflow also need to be defined in those languages using the cadence client, which of course can be done in excecution time from a custom DSL, but none of that out of the box as far as I understand.

Thanks in advance for your guidance

**Comment by dmetzgar** [comment]
This use case fits with Cadence. We have several use cases at Uber where DSLs are built on top of Cadence. The typical approach is that when the DSL is updated, a new workflow type is registered (maybe with an incremented version number in the name) and all new workflow instances use the new version of the workflow. There's also a case where the DSL needs to contain Python expressions and the devs chose [Starlark](https://github.com/google/starlark-go) to handle the expression parsing.

**Comment by mfateev** [comment]
If you decide to replicate StepFunctions on top of Cadence we are willing to work with you to make sure that the design and implementation are correct. We also can release a private library we developed that simplifies writing new DSL implementations on top of Cadence.

**Comment by joecabezas** [comment]
thanks for the answer, why DSL for workflow this is not the default in Cadence?

**Comment by joecabezas** [comment]
@mfateev oh that sounds interesting, I want to replicate much of step functions, or at least support the requirements I listed above, the top one being using a simple language agnostic DSL to define a workflow (maybe just using Amazon State Language), and one activity per node type, like a `URLActivity` which receives an endpoint to call and based on the result advance to a specified next node (I think that conditional behavior can be in the workflow code)

**Comment by mfateev** [comment]
Copying my answer from [hackernews](https://news.ycombinator.com/item?id=19732447):

[-]DSL is DOMAIN specific language. But it is common mistake to call GENERIC workflow definition a DSL. My opinion is that DOMAIN specific languages are awesome when they are used for a specific narrow domain. For example AWS CloudFormation template is a DSL for a cloud deployment. If This Then That, also known as IFTTT is another good example of a narrow workflow definition.At the same time a generic turning complete language in JSON/YAML/XML always starts simple but ends up as a complete mess. See [The Configuration Complexity Clock](https://mikehadlow.blogspot.com/2012/05/configuration-complexity-clock.html). Any programming language is much better for writing complex programs. The problem is that most existing workflow/orchestration systems force developers to use unnatural programming patterns and libraries to make the code fault tolerant. Cadence is an attempt (pioneered by my team at AWS Simple Workflow and later picked up by Azure Durable Functions) to implement workflows as natural programs without much boilerplate concepts and code.Think, why nobody tries to write complex backend programs in JSON? The reason that programming languages have well defined ways to deal with complexity. JSON based languages are good for limited domains, but anything complex makes them unusable. I've seen it hundreds of times already when DSL is abused and developers hate it.So most of the Cadence workflows are written directly as Go/Java code. But when DSL is appropriate it can be added trivially by interpreting it by the worker code.

`Again - the same question: wouldn't it have been better to have a uniform declarative JSON ?
`
Again, declarative JSON is declarative only in narrow domains. The generic workflow definition language in JSON works only for very simple scenarios and is harder to write and debug then Go/Java code.

**Comment by joecabezas** [comment]
@mfateev thanks for the insight, I understand, specially when you mention testing, which is more natural in a programming language rather than a DSL, previously when working with other workflow engines we could only automatically test the endpoints but not the business logic of the workflow itself, which can be done now using non DSL approach.

**Comment by aiyi** [comment]
> If you decide to replicate StepFunctions on top of Cadence we are willing to work with you to make sure that the design and implementation are correct. We also can release a private library we developed that simplifies writing new DSL implementations on top of Cadence.

Thanks to the great design of Cadence, I’ve been actually doing good in implementing AWS states language on top of Cadence. I wonder if there is any mechanism Cadence already support to associate the state specific info (e.g. state name, input/output) with workflow history event, so that render a runtime graph like StepFunction console does can be achieved by quering workflow execution info. Or I should do this in a different way. I’d appreciate your advices.

In respect of the private lib you mentioned for DSL, may I know the features to ease the DSL development. Thanks a lot.

**Comment by mfateev** [comment]
For rendering we recommend using queryWorkflowExecution feature. The basic idea is that the query is a callback into the workflow code and you can return any information about your workflow state. 
Could you point us to your repository? We can help with code reviews.
[Here is](https://github.com/samarabbas/cadence-samples/tree/master/cmd/samples/recipes/query) the query sample in Go.  And [here is ](https://github.com/uber/cadence-java-samples/blob/master/src/main/java/com/uber/cadence/samples/hello/HelloQuery.java) one in Java.

**Comment by aiyi** [comment]
> For rendering we recommend using queryWorkflowExecution feature. The basic idea is that the query is a callback into the workflow code and you can return any information about your workflow state.
> Could you point us to your repository? We can help with code reviews.
> [Here is](https://github.com/samarabbas/cadence-samples/tree/master/cmd/samples/recipes/query) the query sample in Go. And [here is ](https://github.com/uber/cadence-java-samples/blob/master/src/main/java/com/uber/cadence/samples/hello/HelloQuery.java) one in Java.

Great idea, again. The query handler solved my problem. The repo is a private one for now. I'd like to open the source when everything is ready.

**Comment by bjacobso** [comment]
@joecabezas @aiyi I have been working on a proof of concept for States Language on top of Cadence here: 
https://github.com/checkr/states-language-cadence

Still a few things missing but it seems more than doable.
