### ISSUE TITLE
Improve Scan in batch operation

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#2154]
We are using scan API in batch operation but this could be in-efficient in case of batch operation takes very long time-- scan will be taking the ES resources until batch is done. As ES scan resrouce is expensive, we want scan to be finished as soon as possible. 
Ideally we want to do a quick scan and dump all the results into a file, and then process the file.

**Comment by vancexu** [comment]
Another issues around this is: to batch terminate cron workflows. 
Says I have 100k open cron workflows which continueasnew every 10 mins. I batch terminate using query of all open workflows, batch job takes longer than 10 minutes, and scan workflow result is returning workflow executions which already had new run (because scan hold a window of result at the query time). Then once the batch completed, you may see there are still 60k workflows open.
