### ISSUE TITLE
Cadence cli `get-search-attr` and update search attr should not require domain

### ISSUE THREAD

**Issue by shreyassrivatsan** [uber/cadence#2329]
Search attributes are global for a cluster. It should not require a domain as input to run the operation.

**Comment by vancexu** [comment]
All CLI operations currently requires domain as global option, to init client and create related metrics. This has a benefit that we can know which domain made the CLI calls. 
I agree `get-search-attr` doesn't need domain itself, but I don't think it worth to make the change (because it will be the only cmd doesn't require domain and cannot be tracked), unless we have more commands doesn't requires domain.

**Comment by shreyassrivatsan** [comment]
Ok, that makes sense. But there is one more thing (I forget now) which is global but we end up doing it at domain level due to this limitation.. We should keep track of these and when we get a chance and handle the global stuff.

**Comment by mikolajb** [comment]
But admin operations do not require a domain, right? It makes the commands look a bit inconsistent:
`cadence adm cl add-search-attr --search_attr_key RolloutID --search_attr_type 1`
for creating a search attribute, and
`cadence --domain "whatever" cl get-search-attr`
for listing them.

**Comment by vancexu** [comment]
This was fixed and will be available in CLI 0.9.0
