### ISSUE TITLE
Matching Engine: Dispatching task to zombie pollers

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#254]
Looks like we don't tear down the connection immediately for long polls when a worker dies.  This results in us dispatching tasks to those zombie pollers.  This is very bad experience as the task needs to timeout before we can dispatch it again, and seems like stuck workflow from user perspective.

Repro Steps:
1) Start worker
2) Run one workflow till completion (HelloWorldExample)
3) Kill worker (Ctrl-C)
4) Trigger another workflow while worker is down: ./bin/helloworld -m trigger
5) Bring up worker

You should see the decision task is not picked up instantly by the worker.  It only starts after the decision times out and new decision task is created.

**Comment by madhuravi** [comment]
The commit #183 did not fix this issue. tchannel-go does not support context cancel propagation. So the current approach with client calling cancel before shutting down will not send any signal to the server.

**Comment by madhuravi** [comment]
Tried a few transport level fixes -
Client side:
Call channel.Close when client receives shutdown -> The tchannel close method does not force close connections, it simply waits for existing connections to finish. This does not help since we want to short-circuit and exit.

Server side:
Call Ping to verify client is up 0> Ping takes a host port and we don't know which host port made this specific call.
Set call back function on tchannel status change -> Again we have multiple connections open to server, we need to know more identifying information than just a status change. This might be worth exploring further to see if we can get more information from this call.

**Comment by madhuravi** [comment]
The feasible option seems to be to implement an isAlive mechanism in the tchannel library. However tchannel is not in active development and we might switch transport to YARPC/gRPC soon. So this is shelved until migration.
