### ISSUE TITLE
cadence-sql-tool is not  properly taking password with special characters

### ISSUE THREAD

**Issue by aned** [uber/cadence#2679]
```./cadence-sql-tool --user cad_admin --pw "blah{blah"   some_other_flags``` 

Tried single/double quotes, no luck.

**Comment by sevein** [comment]
@aned, I can't reproduce. I've tried with a a few combinations using special characters, e.g:

    alter user 'cad_admin'@'%' identified by '%}8;s_rplJNS>[}lNG/k,Lt[f5\\b2z*>>Mwx<';

Notice that the string literal above uses the `\\` escape sequence so I can have a backslash in my password. The following works for me:

    cadence-sql-tool --user cad_admin --password "%}8;s_rplJNS>[}lNG/k,Lt[f5\b2z*>>Mwx<" some_other_flags

So I'm wondering if the problem is in your [MySQL string literals](https://dev.mysql.com/doc/refman/8.0/en/string-literals.html). Ultimately if there is a bug here I think it would be in [github.com/go-sql-driver/mysql](https://github.com/go-sql-driver/mysql but [ParseDSN](https://github.com/go-sql-driver/mysql) really seem to be doing this right and they have [tests](https://github.com/go-sql-driver/mysql/blob/296987f946840022593fa9179ee8cfb58307caf5/dsn_test.go#L48) for this case.

**Comment by aned** [comment]
Thanks for looking into it @sevein, I'll test it again when deploying new cadence release.
