### ISSUE TITLE
Cadence does not support TLS for Cassandra/MySQL

### ISSUE THREAD

**Issue by vsabella** [uber/cadence#2681]
Currently we run our MySQL and Cassandra clusters using TLS. Looking for TLS support in Cadence and in the toolchains (like cadence-cassandra-tool)

https://godoc.org/github.com/gocql/gocql#SslOptions

**Comment by vsabella** [comment]
Additionally, it looks like there are multiple implementations of Cassandra wrappers - some for CLI tools and some for the persistence store. Is there any desire to unify these?

**Comment by PankajWorks** [comment]
@mfateev since tls for cassandra is already done. wanted to check what is the plan around this.

**Comment by mfateev** [comment]
@PankajWorks We don't have concrete plans and resources to work on it in the next couple of months. Any contributions in this area are welcome.

**Comment by PankajWorks** [comment]
We are working on this issue for mysql. **We are proposing the approach here so that we can get some feedback. One key requirement we are trying to solve is the ability to specify TLS validation as well - which necessitates the use of the [mysql.RegisterTLSConfig](https://godoc.org/github.com/go-sql-driver/mysql#RegisterTLSConfig) and required parameters. The changes include:**

- Introduce a "enableTLS" flag to enable/disable custom TLS Configuration. It will set  tls="custom" as DSN attribute

- If enableTls flag is set to true , the user will have to provide different certificates as required by [mysql.RegisterTLSConfig](https://godoc.org/github.com/go-sql-driver/mysql#RegisterTLSConfig) to make a secure connection i.e.
    - cacert - The path name of the Certificate Authority (CA) certificate file.
    - tlscert - The path name of the client public key certificate file.
    - tlskey - The path name of the client private key file.
-  If user decides to add tls as part of connectAttributes and enableTls is not specified, then that value will be used while constructing DSN. 
if tls is used as part of connectAttributes along with enableTLS=true then tls value present in connectAttributes will get overridden by custom TLS configuration.
**We would like to work on this for MySQL first. Postgres TLS support can be added once MySQL support is in**.

**Comment by bjacobso** [comment]
@PankajWorks @SachinHg 

I have a PR to add support TLS here:
https://github.com/uber/cadence/pull/2913

Does this accomplish what you are trying to achieve?
