### ISSUE TITLE
Not compatible with Elasticsearch 7.x

### ISSUE THREAD

**Issue by mingfang** [uber/cadence#2866]
https://github.com/uber/cadence/blob/5e0a62bd2acaf2aae8e60547cbcce9b0b86d1fa7/docker/start.sh#L44

fails with an error about include_type_name

**Comment by vancexu** [comment]
We are using `elasticsearch-oss:6.5.1` and didn't get chance to exactly testing against ES7+. But according to a brief skim on https://www.elastic.co/guide/en/elasticsearch/reference/7.x/breaking-changes-7.0.html there shouldn't be major breaking changes affecting cadence ES usage. 

The start up logic is to put index template, is that something you can work around?

**Comment by alexshtin** [comment]
Just tried to run integration tests over latest version 7.5.0. Got:
```
The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true.
````
on test setup stage.

**Comment by vancexu** [comment]
> The mapping definition cannot be nested under a type [_doc]

I did a quick search and here is a simple work around for ES7 https://github.com/uber/cadence/commit/97930e5cadd04a325f4aa0e52b1ccc64ff94bcbe.
(But I cannot checkin this code because it is breaking for ES6)

> https://github.com/uber/cadence/blob/5e0a62bd2acaf2aae8e60547cbcce9b0b86d1fa7/docker/start.sh#L44
> 
> fails with an error about include_type_name
change docker/start.sh `URL="http://$server:$ES_PORT/_template/cadence-visibility-template"` to 
`URL="http://$server:$ES_PORT/_template/cadence-visibility-template?include_type_name=true"` and update search API as above example.

**Comment by kelnos** [comment]
I'm running into this as well.  Another thing that works is to create a new JSON file with just the contents of the `_doc` element (_not_ including the `_doc` element itself), and PUT it to `/cadence-visibility-dev/_mapping` after creating the index.  That should be more future-proof since `include_type_name` will be removed in ES 8.x.

The `number_of_shards` and `number_of_replicas` settings will need to be set separately on the index, of course.

**Comment by longquanzheng** [comment]
@kelnos @mingfang ES7 is now formally supported without the hack in master build. It will be included in the coming release. LMK if you run into any issues. Thanks.
