### ISSUE TITLE
Archival basic query interface doesn't work with S3

### ISSUE THREAD

**Issue by sokada1221** [uber/cadence#3544]
**Describe the bug**
Archival basic query interface always returns:
`only operation = is support for CloseTime`

**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
1. Configure S3 for the visibility archive
2. Try to query from Cadence web

**Expected behavior**
1. Basic query interface to work (to be addressed in https://github.com/uber/cadence-web/issues/208)
2. Improved error message (at least fix the grammar)

**Screenshots**
![image](https://user-images.githubusercontent.com/43149041/93965738-e62a2280-fd30-11ea-9a15-a442e13dc1a4.png)

**Additional context**
N/A

**Comment by longquanzheng** [comment]
Looks like the error is from 
https://github.com/uber/cadence/blob/fa1a3a63074246b3152561e9be53702b5596c834/common/archiver/s3store/queryParser.go#L180

@jontro is the contributor to this package. Could you help take a look?

**Comment by jontro** [comment]
Hi, the query syntax is documented here: https://github.com/uber/cadence/blob/master/common/archiver/s3store/README.md

Date range queries are not supported by the s3 archiver due to how things are stored in s3. To be able to query histories this way I think a different backend for visibility like elasticsearch or dynamodb should be written.

Also the query syntax is left up to the implementors as written here in the implementation guide: https://github.com/uber/cadence/blob/master/common/archiver/README.md

Currently the best way is to use the advanced button and write the query manually. It would be nice if the ui defaulted to this view for the archivers

**Comment by yycptt** [comment]
It's maybe a cadence web issue? It seems like an invalid visibility archival query was sent to the server. 

Can you try using CLI command to query the archived workflows: `cadence --do <domain> wf listarchived -q 'query in s3 syntax'`? If this works then it must be a cadence web issue and I can open an issue there. Thanks.

**Comment by sokada1221** [comment]
Thank you folks!

Yes, it's the UI issue but I also found some backend message issues so I opened it here.
Just opened a new separate issue dedicated for the UI portion. https://github.com/uber/cadence-web/issues/208

I'll work on the backend message issues right away as I have a little capacity now.

**Comment by meiliang86** [comment]
Thanks @sokada1221. Feel free to open a PR and we will help review.
