### ISSUE TITLE
Allow restart(reset) without reapplying signals

### ISSUE THREAD

**Issue by jiaxuyang** [uber/cadence#3556]
**Is your feature request related to a problem? Please describe.**
We use signal to implement human task which is recommended in cadence document. 
When we reset a running workflow containing signals, a fresh workflow instance which doesn't contain any old history event is expected, but signals remain in new workflow history.

**Proposed Solution**
Allow a fresh style of reset operation without old signals.
Add documents explaining why we need signal reapplication.

**Additional context**

**Comment by longquanzheng** [comment]
> Add documents explaining why we need signal reapplication.

HI Jiaxu, I built this reset feature so may have more context.  The reason is that in some use cases, people take signals as valuable external events, so when they use reset to reset some bad progress, they want to preserve them after reset. 

But it's case by case, we also saw some use cases don't need reapplying signals. One decision we made was that if you want your workflow to ignore some old signals, you should be able to do that if the signal contains enough information like timestamp. 

I fully understand that it's much more convenient with an option to ignore signals. So I would support your proposal. 
It's not very difficult to implement IMO. It should be small item if some one familiar with Cadence code base. 

I will mark it as up for grabs to see anyone interested. I can offer help/tutoring to write the code.

**Comment by longquanzheng** [comment]
It's done in master, it will be in next release.  @jiaxuyang
