### ISSUE TITLE
cadence_errors and cadence_requests metrics should have "domain" label in prometheus's /metrics

### ISSUE THREAD

**Issue by aned** [uber/cadence#3766]
**Is your feature request related to a problem? Please describe.**
cadence_errors and cadence_requests metrics are missing "domain" label in prometheus's /metrics
Any other related metric (for example cadence_errors_bad_request, cadence_errors_service_busy, etc) have "domain" label attached.

**Proposed Solution**
cadence_errors and cadence_requests metrics should have "domain" label attached. It probably makes sense to do a sanity check if any other metrics are missing "domain" label too.

**Comment by longquanzheng** [comment]
@meiliang86 I generally agree to put domain labels whenever it's available. It doesn't hurt anything because there shouldn't be a big number of domains. What do you think?

Also, there are requests don't have domain tag can be attached. For example, `ListDomains`,  `GetClusterInfo` etc(mostly cluster level APIs). do you think we can leave the tag value empty(make it difficult to filter) or put a default value(looks a bit weird)?

**Comment by longquanzheng** [comment]
@aned very strange, I read through the code but apparently there is no difference in terms of domain tags when server emit metrics for cadence_error and cadence_errors_bad_request. Are you using the latest release? If so I probably need to run  prometheus locally to understand more

**Comment by aned** [comment]
@longquanzheng we're on {branch="v0_14_0_branch", build_date="2020_09_14_18_57_34", build_version="v0_14_0", revision="aa6b8a97"}
Unless there was a bug that was fixed in 0.15+ I think the bug remains.

**Comment by longquanzheng** [comment]
@aned You are correct that some cadence_errors and cadence_requests are missing domain label. And they are all from History or Matching service. 

For History service, I attempted to add the domain label in https://github.com/uber/cadence/pull/3786 , but I realized that most requests passing into history service don't have domain, because domain already converted into domainUUID internally. Emitting domainName label requires converting it back to domain....which technially is possible but a bit inefficient. We should do it when that become really necessary. 

For matching service, it is intentionally missing in https://github.com/uber/cadence/pull/3155 . The metric with domain+tasklist version is XXX_per_tl : cadence_requests_per_tl and cadence_error_per_tl . So if you need to look at the metric with domain for matching service, use that instead. (I know it's a little weird, maybe we should swap cadence_error_per_tl=>cadence_error, and create cadence_error_agg). 

However, I think what you really need is https://github.com/uber/cadence/pull/3785 because:
1. Mostly from customer PoV they need to set up monitor on domain level cadence_request/cadence_errors for cadence-frontend service. Frontend service is the gateway for all requests. 
2. I think you want to monitor the health of each domain, in that case cadence_error and cadence_requests with domain level on frontend side and matching should be sufficient. 
3.  The history service metrics are very internal only for operation, Cadence team haven't relied on domain tag for very large scale clusters. You should use it for whole cluster monitoring and operation, not for specific domain :D 

LMK if I missed anything

**Comment by aned** [comment]
Thanks @longquanzheng for a deep dive, it makes sense. 
Indeed,  #3785 should do the trick!
