### ISSUE TITLE
[Question] What if client restarts while waiting for workflow results?

### ISSUE THREAD

**Issue by archerbj** [uber/cadence#3792]
I am thinking to migrate our application from raw MQ to Cadence for async requests.

Based on my view, a client can start a workflow and wait for its results. But if the client was accidentally shut down, how to get the upcoming result? Formerly, we use MQ to receive results, and if the client application shuts down during processing the message, MQ will keep and resend the message once the client restarts.

That's totally automatically. The client application doesn't need to do message polling or something.

I think Cadence should have some considerations about it. Could someone tell me how to do this or where the docs are about this question?

And furthermore, how can a client can be notified that the workflow it started has timeout or just failed.

**Comment by longquanzheng** [comment]
Use ExecuteWorkflow API instead of StartWorkflow. It will wait for completion and return the result. 
When starting a workflow, it will attempt to start but if one exists, then use existing instead.
So make sure you pass in a stable workflowID, so that when your application restart, it will still continue to wait for the same workflow(instead of starting a new one).

https://github.com/uber-go/cadence-client/blob/6f6bacf83b870b6d407e665c7dccab22c2f24165/internal/internal_workflow_client.go#L268

This is the same behavior if you use observe command. See my answer here: https://stackoverflow.com/questions/64968166/how-to-make-a-workflow-run-for-an-infinitely-long-duration-when-running-it-using/64973788#64973788

See API 
For Golang: https://github.com/uber-go/cadence-client/blob/6f6bacf83b870b6d407e665c7dccab22c2f24165/client/client.go#L110
Java: https://www.javadoc.io/doc/com.uber.cadence/cadence-client/latest/com/uber/cadence/client/WorkflowClient.html

**Comment by longquanzheng** [comment]
>So I should store the workflow id in db or somewhere else
Yeah, or you use a stable identifier from your business -- for example, Uber driver ID

> But what about the options passed in ExecuteWorkflow? If the workflow exists, Does the new ExecuteWorkflow use former options?
Yes, if workflow already started, it won't use the new options passing in. 

>To be honest, I'd love to see an auto client state recover
Not very sure what you need here. But I feel like it's already doing what you need. And like you said, as you write more Cadence code, you may get better idea. And maybe you can bring up a proposal if you see something we can improve on.

**Comment by archerbj** [comment]
Fair enough! Thanks for your time!
