### ISSUE TITLE
Consuming  Kafka messages to expose workflow status events for consuming

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#3798]
**Is your feature request related to a problem? Please describe.**
Today it's hard to get notification about workflow statuses out side of workflows. For example, people may want to know when workflows fails or timeouts. The best way to monitor is through metrics. However, metrics can only provide it on a domain/workflowType level(timeout metrics is emitted by server). 

**Proposed Solution**
In current advanced visibility design, cadence server is [sending](https://github.com/uber/cadence/blob/a201ed7523381f5875f3c20da4127b0f1cc6a135/common/persistence/elasticsearch/esVisibilityStore.go#L703) the workflow status events to Kafka topic, and then a background task consuming the messages of status event to update ES docs. 

But right now it's binded to run together. It should be decoupled, and allow running Kafka alone if customers don't need advanced visibility.

Also we need to better document the format of messages of workflow status events. 

**Additional context**
N/A

**Comment by emrahs** [comment]
Hey @longquanzheng , thanks for the write-up! I totally agree that there needs to be a pipeline that can turn the Cadence events into super useful things like analytics, alerting, etc. However, I have some concerns around the current proposal, such as: 

- Cadence backend does a great job with managing and orchestrating workflows, and I think it should continue doing that only. Your proposal is basically a webhook system, which is a separate problem domain with its own set of problems. I agree that something like this should exist in some shape and form, but it shouldn’t be part of Cadence since it doesn’t really fit into the core value-add of the service.
- In a webhook setup, ideally the registrations should be fully dynamic and configured by the user. Having customer-specific config inside the Cadence configuration is problematic from the separation of concerns perspective as well as possibly causing operational complexities.
- If I understand correctly, the proposal includes executing the webhook callbacks from the Cadence Worker service. Technically, this would make every registered callback URL a downstream dependency. Introducing N number of other downstream services that would need to be called by the Cadence Worker would bring a lot of complexity to the role, such as downstream latency/capacity issues, network partitioning, a new dimension of SLAs etc. I’d prefer keeping the Worker role focused on being Cadence's internal daemon process that does data propagation (ie. ES), house cleaning (ie. archival, db clean-up), etc. 
- A relatively large Cadence cluster (or even a domain) can generate a very high volume of events, and piping all those events through a webhook is probably going to be impractical. In order to make this work better at scale, there needs to be a flexible rules engine in the picture that lets users precisely filter events that they care about so that only the very useful ones end up triggering the webhook. 


Before diving into the details of the design, we should take a step back and discuss which of the subproblems here fit well into the domain of Cadence. I think Cadence should definitely produce a stream of events and it should be decoupled from ES indexing flow. Besides, it should also set contracts & guarantees around the schema and deliveries of those messages to enable building reliable event consumers. However, I’m less sure about what else beyond that should be part of Cadence. Technically, as long as the data is available in an event stream, Cadence users can create standalone services to consume that stream or use an open source rules engine to filter & fan out the events to the interested parties. I think we should first discuss why a generic rules engine solution (ie. Siddhi - https://github.com/siddhi-io/siddhi/) doesn’t work, where the limitations are and why Cadence would do a better job. I think that discussion will help us better understand the requirements from the perspective of Cadence and see if the cost & complexity is worth the benefits.

**Comment by longquanzheng** [comment]
Thanks so much for you comments @emrahs . 

Not very clear about the usage of rule engine here. But if the idea is to let users consume the visibility Kafka topic, then it won't work for the problem. (yeah sorry, we should have a problem statement first). 

We have OSS users came to us after they tried to implement and maintain the system of consuming the Kafka topic, it's very hard and hacky and they want to stay away. There are lots of complexity there. e.g:
* How to decode the Kafka message which are encoded with Thrift today(it's not friendly to every language)
* How to ensure the Kafka consuming is correct and reliably (I have written this part three times for Cadence, it's not trivial)
* How to emit the metrics and logs

Those are common problem that every OSS users need to solve, including Indeed. 

As for scalability concern, I am pretty sure as we implement it in the right way, there won't be any issues. we can talk about more tomorrow. Mostly it's all supported by Kafka partitioning and consumer group model. It's going to be exactly the same way as we did for Kafka->ElasticSearch (which is also HTTP service). 

I just put down these in case you need to know my thoughts before the meeting. But let's talk about it tomorrow :D

**Comment by chrissgyulev** [comment]
Hi guys!
After reading your thoughts, it seems that there is a need of separate visibility service which could run and scale indipendently. 

Regards,
Chriss

**Comment by longquanzheng** [comment]
> Hi guys! After reading your thoughts, it seems that there is a need of separate visibility service which could run and scale indipendently.
> 
> Regards, Chriss

It needs to run on top of advanced visibility. Is that your question? Not sure what you meant by "visibility service".

**Comment by longquanzheng** [comment]
Close since it's done in https://github.com/cadence-oss/cadence-notification
