### ISSUE TITLE
Benchmark cadence workflow engine

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#3860]
Need to measure performance and resource consumed in different scenarios:
1. different persistences 
2. different shard scale
3. different cluster sizes and instance sizes 
4. different work load pattern(workflows)

**Comment by ibarrajo** [comment]
Closing since we have support for bench testing with different workloads, documented here:
https://github.com/uber/cadence/tree/master/bench

**Comment by demirkayaender** [comment]
Looks like this was originally open to provide benchmark infra. That part is done, we consider releasing benchmark results soon too.

**Comment by anumolurahul** [comment]
@demirkayaender are the benchmark results published?

**Comment by demirkayaender** [comment]
This issue was to support an infrastructure to perform a benchmark test but we haven't published bench test results publicly yet. Main reason this wasn't published was because everyone had their own setup with different hardware and provider. Our numbers won't necessarily match yours but to provide an estimation, we can consider publishing one with hardware and test spec we use. Would that work?

**Comment by anumolurahul** [comment]
@demirkayaender sure that should work, we have done a few iterations of bench tests and just want to compare the spec we used and the results we got with yours.

**Comment by demirkayaender** [comment]
What kind of load are you testing with? We can try to run something similar
