### ISSUE TITLE
History scavenger can leave orphaned history_node entries

### ISSUE THREAD

**Issue by kraney** [uber/cadence#4065]
**Describe the bug**
The history scavenger is designed to expire old entries out of the database in both the history_tree table and the history_node table.

When deleting, the scavenger 
1. Loads the history_tree record
2. Deletes the history_tree record
3. Deletes the history_node records that belong to the tree entry

If all goes to plan, this is fine. If step 3 fails for any reason, then any history_node entries that have not yet been deleted do not get deleted. Since there's no longer a history_tree record referencing them, the history scavenger will never pay any attention to them.

**To Reproduce**
- Yes

**Steps to reproduce the behavior:**
* Watch for the history scavenger to run
* Once it has started, kill the worker pod
* Query for orphaned history_node records

**Expected behavior**
* The scavenger really should delete the history_node records first, and only delete the history_tree record once all nodes have been successfully removed.

**Comment by longquanzheng** [comment]
that's interesting. 

I thought the SQL using transaction to delete both history_tree record and history_node record at the same time:
 https://github.com/uber/cadence/blob/b78809c691b08c33bc2e11e6222b0e8fde75d7ee/common/persistence/sql/sqlHistoryManager.go#L396
 
Same for Cassandra, since it's using loggedBatch: 
https://github.com/uber/cadence/blob/b78809c691b08c33bc2e11e6222b0e8fde75d7ee/common/persistence/nosql/nosqlplugin/cassandra/events.go#L125

https://docs.datastax.com/en/dse/6.0/cql/cql/cql_using/useBatch.html
```
Single partition batch operations are atomic automatically
```
(disregarding that we have seen issue in Cassandra resurrection )

**Comment by kraney** [comment]
Hm, perhaps I stand corrected.
