### ISSUE TITLE
(Help needed) Termination handling. Signals to activities.

### ISSUE THREAD

**Issue by polyansky-syberry** [uber/cadence#4167]
We have workflows that must be cleaned up after their executions no matter of the result. This cleanup sends some API calls, does local directory work and so on. This cleanup is implemented by calling final activity that does the work at the end of workflow,
But on termination, the execution stops, current activity stops and we are not able to execute needed clean up.
So we found two possible solutions: using workflow signals to stop workflow execution (simply stop calling new activities except the final one if the signal came); or using cron job that will list terminated workflows and will cleanup them one by one.
All of the solutions have critical issues, that we want to avoid: first approach has to wait till current activity finishes, the second cleans everything up once per time, but we want it to happen right after termination.
Here come 2 questions:
1. Does cadence have some termination handling extension (callbacks may be, or anything, that let us to tell cadence what to do on termination)?
2. Is there possibility to send signals directly to activities? It will allow us to force stop activity execution in case the signal is received.

**Comment by Groxx** [comment]
For the most part, this will be a client-side thing, not server-side (as the server can't really run custom-per-workflow code on completion).  For client-side:
- Termination is the equivalent of `kill -9`, it's effectively "by design" that it doesn't let you run cleanup.  You likely want to _cancel_ your workflows.
- When you _cancel_ a workflow, all that happens is that your workflow's context is cancelled / an exception is thrown, and a new decision task is started on a worker (to process the cancellation).  In your workflow, you can pretty easily detect this, and do whatever you like: run cleanup activities, start child workflows, ignore it and `workflow.Sleep` for a week, etc.
  - For Go: your context is cancelled, and you can use a `NewDisconnectedContext` to do additional stuff: https://pkg.go.dev/go.uber.org/cadence@v0.17.0/workflow#NewDisconnectedContext
  - For Java: I believe this is covered by the `Workflow.newDetachedCancellationScope` docs: https://www.javadoc.io/doc/com.uber.cadence/cadence-client/latest/com/uber/cadence/workflow/Workflow.html
- Timed-out workflows are _effectively_ terminated.  So if you want to run cleanup before timeout: add [X days] to your workflow's execution timeout, start a timer in your workflow that'll fire X days before your workflow times out, and run cleanup funcs at that time.

For true "run after ANY completion", there are a few options, but none of them are as easy to set up.
- You can do what you described: start a cronjob to list terminated workflows (and/or timed out or whatever), and run cleanup processes on them.
  - Note that you can query workflows that are completed.  If you need data from them to do cleanup, just add a query handler to expose that data.
- If you have the elasticsearch setup running, the workflow visibility data (I believe this is a kafka topic?) will contain workflows as they complete, regardless of the reason.  You could for example start a kafka consumer on this topic, and do whatever you need to when you see a workflow that's missing cleanup.
- Fork the server, add something to support your cleanup ¯\\\_(ツ)\_/¯

**Comment by polyansky-syberry** [comment]
Thank you for the response, it is now much clearer.
We use Java client, and I saw the method you mentioned, but I haven't succeeded in using it.
Here is some code, may be I did something wrong:
![image](https://user-images.githubusercontent.com/65544802/116862327-3fcec580-ac0d-11eb-8cb8-2e57f3080e49.png)
![image](https://user-images.githubusercontent.com/65544802/116862356-4cebb480-ac0d-11eb-82ee-18c23a21b278.png)
![image](https://user-images.githubusercontent.com/65544802/116862384-537a2c00-ac0d-11eb-9890-7e1959ffd281.png)
Nothing of those works. Meaning it gets into neither catch block nor in finally when I terminate workflow's execution from both UI or CLI. The only thing I can catch is WorkflowTerminatedException from place where workflow is started:
![image](https://user-images.githubusercontent.com/65544802/116862536-93411380-ac0d-11eb-9621-8c11a2064393.png)

**Comment by Groxx** [comment]
Two sanity checks worth doing:

1: `catch (Throwable e)` is a classic Java mistake, even worse than `catch (Exception e)` - you're catching things like thread interrupts _and ignoring them_, which is how Cadence (attempts to) remove workflows from the cache.  It has no other way of interrupting your code.  Nearly all cases of catching `Throwable` or `Exception` without re-throwing are incorrect.

That said, I sincerely doubt that's causing this to not work.

So, 2: You cannot catch a _termination_ and use a detached scope, by design (well.  `catch (Exception or Throwable)` can _observe_ it.  But the server will reject your new activities, so it hardly matters).  You can only catch _cancellation_.  Make sure you're canceling, not terminating.  On the CLI that's `cadence workflow cancel`, not `cadence workflow terminate`.

Once you're using cancels: I believe any of those first 3 will work, though you should probably stick to the third.  Otherwise you're running on _any_ exception, possibly including normal lifecycle events.

**Comment by longquanzheng** [comment]
Here is a sample for using cancellation in Java: https://github.com/uber/cadence-java-samples/pull/46
