### ISSUE TITLE
Create Docker Image as non-root User

### ISSUE THREAD

**Issue by WToma** [uber/cadence#4790]
**Situation**: automated vulnerability scanners, like Twistlock, are picking up on Docker images using the root user in our production systems. As far as I can tell, and per advise from our infosec team, this does not cause any exploitable vulnerabilities, however it is not a best practice.

**Proposed Solution**: modify the Dockerfile so that in the final server image the cadence binary runs as a non-root user.

**Additional context**: I actually tried making this work in https://github.com/WToma/cadence/commit/8253f388eb6e0b0c8a9f47b6c6abc8d0264bb1e5, however that didn't work, got permission errors on startup trying to read the config file. So more work is needed here.

**Comment by longquanzheng** [comment]
Just a note that you probably run into some permissions issues with write access when doing this. 


Below is my answer in the slack channel: 

https://uber-cadence.slack.com/archives/CKBQ9LTTM/p1632944467001700

It’s a bit tricky You just need to do the same thing Cadence Helmchart does. Essentially, it replace the config_template with the actual config value using volume mounting.
https://github.com/banzaicloud/banzai-charts/blob/master/cadence/templates/server-deployment.yaml#L121
Which I believe, essentially you can do the same in docker volume mouting: https://docs.docker.com/storage/volumes/

So the trick is just  replace the config_template with the actual config, so that the https://github.com/uber/cadence/blob/master/docker/start-cadence.sh#L7 will be a noop
