### ISSUE TITLE
Add callbacks to workflow execution

### ISSUE THREAD

**Issue by bincx** [uber/cadence#4914]
**Is your feature request related to a problem? Please describe.**
Let's say I have a running workflow and I need to update external service with the status of the workflow, whether it finished successfully or failed. Currently, I'm using helper workflow that calls DescribeWorkflowExecution() where the workflowID is the same with every retry and runID is empty string, so I can get the exit status of the monitored workflow.

**Proposed Solution**
I would like to have callback functions passed either as StartWorkflowOptions() or as workflow arguments that will be called in case of success of failure of the workflow.

**Additional context**
I'm wondering if scanning workflow history by running DescribeWorkflowExecution() is not too much overhead.

**Comment by demirkayaender** [comment]
We are planning to build this in H2, feature called workflow notifications. You can subscribe to a workflow and get notified each time there's an update, if you hit a specific check point or if the workflow completes based on your settings. It's in the works. 

If you want to use this as a sync API you can try `ExecuteWorkflow(…).Get(…)` instead of `StartWorkflow` API.
https://github.com/uber-go/cadence-client/blob/master/client/client.go#L79
https://github.com/uber-go/cadence-client/blob/master/internal/internal_workflow_client.go#L91

**Comment by demirkayaender** [comment]
Some people also use `GetWorkflowHistory` with `longPoll = true` for this purpose: https://github.com/uber-go/cadence-client/blob/master/client/client.go#L196

**Comment by demirkayaender** [comment]
Closing this for now, feel free to reopen it towards the end of the year if you still have issues.

**Comment by dogenkigen** [comment]
@demirkayaender have you managed to implement the workflow notifications you mentioned?
