### ISSUE TITLE
Include parent workflow execution on both describe and list api

### ISSUE THREAD

**Issue by samarabbas** [uber/cadence#745]
Parent workflow execution information is not exposed to users through both describe and list workflow execution apis.  
This task is to expose parent information on the following APIs:
- DescribeWorkflowExecution
- ListOpenWorkflowExecutions
- ListClosedWorkflowExecutions

**Comment by emrahs** [comment]
Hey @samarabbas! I see that the DescribeWorkflowExecution API already returns the parent execution information. On the other hand, the list APIs don't return it (ie. the field is in the response, but is always nil). I see the value of having the parent information in the DescribeWorkflowExecution API but I'm not sure if having it in the List APIs is equally valuable. 

Given that the visibility tables don't have the columns for parent execution information, I wonder if it's worth the effort to alter the schema. Depending on the use case, clients might be able to get away with calling the DescribeWorkflowExecution API on a per workflow basis.

Please let me know if you are aware of use cases where having the parent execution information in the list APIs is really needed. Otherwise, I'm going to close this ticket for now.

**Comment by meiliang86** [comment]
Closing per comment above.
