### ISSUE TITLE
Document prod setup instructions - getting version mismatch errors

### ISSUE THREAD

**Issue by ryanwalls** [uber/cadence#747]
We are now running cadence and cassandra in our production cloud environments.  We have an issue where if the cadence server restarts it prints out a schema mismatch error.  Something along the lines of "expected version 0.0 but got version 0.5".  Our docker container then exits and Kubernetes restarts it indefinitely.  

This document https://github.com/uber/cadence/tree/master/docker#quickstart-for-production implies we can run cadence without the schema setup, but the `SKIP_SCHEMA_SETUP` flag doesn't seem to avoid the error above.  

Would also need documentation on how to setup the cassandra schema separately from the cadence server.

**Comment by samarabbas** [comment]
You should never be deploying Cadence server without schema setup.  We have a check in place on service startup to reconcile the schema with the version of service.  
Please look at the readme for [schema update tool](https://github.com/uber/cadence/tree/master/tools/cassandra).  It has instructions on running the tool on a brand new cluster or an existing cluster.
Process for upgrading new Cadence server is pretty straightforward.  
1) Look at release notes to see if it has schema updates.
2) Run the tool to upgrade the schema to release you are upgrading to.
3) Then upgrade Cadence application

All our Schema changes are backwards compatible unless mentioned in the release notes.  In which case we will provide specific instructions for that release.

**Comment by samarabbas** [comment]
@ryanwalls we expect schema setup to be run by docker container for local dev setup only.  This is to allow developers to write and test workflows locally.  It does not makes sense to deploy schema on container startup for production clusters as most likely you would want multiple containers running.
A while back a developer on our team wrote some scripts to deploy Cadence on AWS.  I highly recommend you to check it out:
https://github.com/longquanzheng/cadence-aws

I also noticed you are using Cadence version '0.3.9', is this intentional?  This build is couple of months old.

**Comment by ryanwalls** [comment]
@samarabbas Thanks for the link to the AWS scripts.  For the ubercadence/server image, is there a way to turn off the schema setup?  

Regarding 0.3.9 version, we just hadn't taken the time to upgrade yet.  Will do that today.

**Comment by samarabbas** [comment]
You can use 'SKIP_SCHEMA_SETUP' flag to skip running the tool on start up.

**Comment by venkat1109** [comment]
I believe this is not actually caused by the SKIP_SCHEMA_SETUP setting.

The problem is likely with this code
https://github.com/uber/cadence/blob/858b8f4b931cd2044bccd023d83486cc9577c4db/cmd/server/cadence.go#L62

Which attempts to validate that the schema version is compatible with code at bootstrap time. It has assumptions about the directory structure that contains the schema/ directory within the container, which might have been broken with the setup above - {kubernetes / docker}

**Comment by dibeshdas151995** [comment]
Do I need docker to setup cadence locally?
