### ISSUE TITLE
CLI: Improve listworkflow with friendly date range 

### ISSUE THREAD

**Issue by vancexu** [uber/cadence#825]
Currently CLI `workflow list` takes -et -lt as UTC and UnixNano, which is not human friendly. 
Need to improve it to list last 1 hour, last week etc.

We can also think about replace existing datetime parser to something like https://github.com/araddon/dateparse, which relax on datetime format.

**Comment by kaustubhmallik** [comment]
@wxing1292 Is it still open to grab? If so, I would be more than happy to help.

**Comment by vancexu** [comment]
@kaustubhmallik Yes it is. It would be great if you can take it.

**Comment by kaustubhmallik** [comment]
@vancexu I would love to. Have you given any thought about it already? Or should I come up with my approach, and maybe you can guide me further.

**Comment by kaustubhmallik** [comment]
Hi @vancexu, I have thought of doing it in the following manner.

The argument would look like - ```last <num><duration>```

Users are supposed to put quotes (single/double) around the argument just like any other *nix argument to be treated as one argument.

- num  - positive integral value (1e6 > num > 0 ). ZERO and negatives are considered invalid value. If num is skipped, a default value of ONE is considered.

- duration - possible values for duration will be (full name/short name):
        - second/s
        - minute/m
        - hour/h
        - day/d
        - week/w
        - month/M
        - year/y

The maximum duration can go as back as Unix epoch time (1 Jan 1970 00:00:00 UTC), as we are already using Unix timestamp, so it will be compatible with it.

For example, some possible arguments can be (each row have equivalent arguments):
* last 1second, last 1s
* last 10 minute, last 10m
* last hour, last h, last 1h
* last 4 week, last 4w
* last month, last M, last 1M
* last 1year, last 1y, last y

Let me know if this sounds good to you, or if there are some improvements/suggestions, I would love to hear it.

**Comment by vancexu** [comment]
@kaustubhmallik  The proposal sounds good.

**Comment by kaustubhmallik** [comment]
Now that would be awesome! Do you want to add that in the same proposal, or you want to do that separately? I guess it might be better if we can handle it separately, but please suggest what you feel like.

**Comment by vancexu** [comment]
> Now that would be awesome! Do you want to add that in the same proposal, or you want to do that separately? I guess it might be better if we can handle it separately, but please suggest what you feel like.

Yes, agree it's better to do separately. Just share some idea for next.

**Comment by kaustubhmallik** [comment]
In order to enter the time range, I can think of two ways:

1. To put some separator in the argument to separate the time range `--et "<range_start_time> | <range_end_time>"`
eg. `--et "last 1d | last 3d"`. 
We can make it mandatory to specify start time first, and end time second. In the absence of separator, it will behave as it is now, so it will be backward compatible. We can think of other separators also, but I will avoid comma as it usually means that you are giving a set of discrete values as an argument.

2. To add nested arguments to provide a time range, like `--et --start "last 1d" --end "last 3d"`.

At first look, second looks more clear from a user perspective, but it might result in confusion also, if someone wants to use it the way before, as in that case no start or end args will be needed. Like, what if someone just gave one of them, assuming the other take some default value. 
eg. `--et --end "last 1d"`, so a user assumes in this case, the start time will be the current time. 

Equivalently, a better way to write this is `--et "last 1d"`. Similarly, if someone just gave the start and misses the end, we can’t know what the end time, and have to raise en error.

So, in my opinion, the first looks more concise and will work better with the existing users, who want to try out this new feature.

Let me know what you think about it. I would love to hear some suggestions/improvements to it. Also, please let me know if I should start working on the previous thing, in which case please assign the issue. It helps me to keep track of things 😃

**Comment by mfateev** [comment]
@kaustubhmallik I might be missing something but CLI has already two options:

```
   --earliest_time value, --et value           EarliestTime of start time, supported formats are '2006-01-02T15:04:05+07:00' and raw UnixNano
   --latest_time value, --lt value             LatestTime of start time, supported formats are '2006-01-02T15:04:05+07:00' and raw UnixNano
```
What is the problem to keep using both of them without introducing the new ones? So your example becomes:

`--et "last 3d" --lt "last 1d"
`

**Comment by kaustubhmallik** [comment]
Hi @mfateev, thanks a lot for reviewing it. My sincere apologies, as I didn't know that we can use both options at the same time. It looks it's already serving the purpose perfectly.

@vancexu What your views on it?

**Comment by vancexu** [comment]
Ok, then I think we can just do `--et 3d --lt 1d` (because last is redundant). 
I previous thought `--et` followed by a during (not a timestamp) is a little bit inconsistent, so leaned on `-last 3d`. But now it looks like `--et 3d --lt 1d` has more benefits. 
I assigned the task to you @kaustubhmallik

**Comment by kaustubhmallik** [comment]
True! It make sense to drop `last`, also makes it a bit easier to use. Thanks for assigning it, I will try to finish the code changes soon and will let you know if I face any problem.

**Comment by vancexu** [comment]
> True! It make sense to drop `last`, also makes it a bit easier to use. Thanks for assigning it, I will try to finish the code changes soon and will let you know if I face any problem.
> 
> Also, as we are dropping the last keyword, it makes sense to make the numeric multiplier as mandatory. So, finally, the argument will be like:
> 
> `--et <num> <duration>` or `--lt <num> <duration>` or combination of both
> 
> `<num>` - **mandatory**, integer, 0 < num < 1e6
> `<duration>` - **mandatory**, string, possible values
> 
> * second/s
> * minute/m
> * hour/h
> * day/d
> * week/w
> * month/M
> * year/y
> 
> Some example values:
> 
> * `--et 1w`
> * `--et 2d`
> * `--et 2d --lt 1s`
> * `--et 1M --lt 1w`
> * `--et 3M`
> * `--lt 1h`
> 
> Let me know if this is good to go, so I will start the implementation, and raise a PR at the earliest.

@kaustubhmallik looks good, go ahead

**Comment by vancexu** [comment]
Thanks again for your contribution!
